# Generated by Django 2.2.1 on 2019-05-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.CharField(max_length=70)),
                ('profession', models.CharField(max_length=70)),
                ('date_started', models.DateField()),
                ('course_teaching', models.CharField(max_length=100)),
                ('working_status', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
            ],
        ),
    ]
