# Generated by Django 2.2.1 on 2019-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='date_started',
            new_name='date_employed',
        ),
        migrations.AddField(
            model_name='trainer',
            name='id_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
