# Generated by Django 2.2.1 on 2019-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20190528_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
